### ISSUE TITLE
initialize the framework

### ISSUE THREAD

**Issue by lychee-yycy** [zzxyb/wsm#1]
- [x] init project https://github.com/zzxyb/wsm/commit/bac8c8afb53b5de7309322dbcf449f3118f08f77 ，generally includes the following functions：
 - text_node,show text display node on scene
 - image_node,show image display node on scene
 - xdg surface display support
 - input、seat、cursor and some protocol implementations
 - github action configuration, support arch linux and debian compilation
 - Debian packaging configuration
 - Note that there are still many missing features
- [x] add support xwayland
- [x] custom graphics node rendering

**Comment by zzxyb** [comment]
finished!
